import type { IconType } from "react-icons";
import {
  SiReact,
  SiNextdotjs,
  SiNodedotjs,
  SiTypescript,
  SiTailwindcss,
  SiChartdotjs,
  SiSocketdotio,
  SiFirebase,
  SiExpo,
  SiStripe,
  SiShopify,
  SiGooglemaps,
  SiPostgresql,
  SiPython,
  SiGraphql,
  SiDocker,
  SiKubernetes,
  SiTensorflow,
  SiTerraform,
  SiFlutter,
  SiApachekafka,
  SiAuth0,
  SiExpress,
  SiMongodb,
} from "react-icons/si";
import { FaAws } from "react-icons/fa6";
import { TbBrandAzure } from "react-icons/tb";

/** Maps a technology's display name (as used in content files) to its brand icon. */
export const TECH_ICONS: Record<string, IconType> = {
  React: SiReact,
  "React Native": SiReact,
  "Next.js": SiNextdotjs,
  "Node.js": SiNodedotjs,
  TypeScript: SiTypescript,
  "Tailwind CSS": SiTailwindcss,
  "Chart.js": SiChartdotjs,
  "Socket.IO": SiSocketdotio,
  Firebase: SiFirebase,
  Expo: SiExpo,
  Stripe: SiStripe,
  "Stripe Issuing": SiStripe,
  Shopify: SiShopify,
  "Google Maps": SiGooglemaps,
  PostgreSQL: SiPostgresql,
  MongoDB: SiMongodb,
  Python: SiPython,
  GraphQL: SiGraphql,
  Docker: SiDocker,
  Kubernetes: SiKubernetes,
  TensorFlow: SiTensorflow,
  AWS: FaAws,
  "AWS SageMaker": FaAws,
  "AWS KMS": FaAws,
  Azure: TbBrandAzure,
  Terraform: SiTerraform,
  Flutter: SiFlutter,
  Kafka: SiApachekafka,
  Auth0: SiAuth0,
  "Express.js": SiExpress,
};
