"use client";

import { useEffect, useId, useState } from "react";
import { useTheme } from "next-themes";

export function MermaidDiagram({ code }: { code: string }) {
  const id = useId().replace(/:/g, "-");
  const { resolvedTheme } = useTheme();
  const [svg, setSvg] = useState<string | null>(null);
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    let cancelled = false;

    import("mermaid").then(async ({ default: mermaid }) => {
      try {
        mermaid.initialize({
          startOnLoad: false,
          theme: resolvedTheme === "light" ? "default" : "dark",
          securityLevel: "strict",
        });
        const { svg: rendered } = await mermaid.render(`mermaid-${id}`, code);
        if (!cancelled) setSvg(rendered);
      } catch {
        if (!cancelled) setFailed(true);
      }
    });

    return () => {
      cancelled = true;
    };
  }, [code, id, resolvedTheme]);

  if (failed) {
    return (
      <pre className="overflow-x-auto rounded-lg border border-ss-border bg-ss-base p-3 text-xs text-ss-muted">
        {code}
      </pre>
    );
  }

  if (!svg) {
    return (
      <div className="flex h-24 items-center justify-center rounded-lg border border-ss-border bg-ss-base text-xs text-ss-muted">
        Rendering diagram…
      </div>
    );
  }

  return (
    <div
      className="my-2 overflow-x-auto rounded-lg border border-ss-border bg-ss-base p-3"
      // eslint-disable-next-line react/no-danger -- SVG generated by mermaid.render() with securityLevel "strict"
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
