import type { IconType } from "react-icons";
import {
  TbBrain,
  TbRobot,
  TbSparkles,
  TbEye,
  TbLanguage,
  TbMessageChatbot,
  TbBulb,
  TbChartLine,
  TbCpu,
  TbTool,
  TbApps,
  TbAdjustmentsHorizontal,
  TbPlugConnected,
  TbMessage2,
  TbSearch,
  TbDeviceDesktopAnalytics,
  TbRoute,
  TbBuildingSkyscraper,
  TbBox,
  TbFlask,
  TbChartDots3,
  TbHeartbeat,
  TbShoppingCart,
  TbUsersGroup,
  TbHierarchy2,
  TbBuildingBank,
  TbShieldExclamation,
  TbActivityHeartbeat,
  TbScan,
  TbAlarm,
  TbTruckDelivery,
  TbHeadset,
  TbBuildingStore,
  TbHierarchy,
  TbTrendingUp,
  TbMicrophone,
  TbVideo,
  TbCameraCheck,
  TbThumbUp,
} from "react-icons/tb";

const ICON_MAP: Record<string, IconType> = {
  brain: TbBrain,
  robot: TbRobot,
  sparkles: TbSparkles,
  eye: TbEye,
  language: TbLanguage,
  chatbot: TbMessageChatbot,
  bulb: TbBulb,
  chartline: TbChartLine,
  cpu: TbCpu,
  tool: TbTool,
  apps: TbApps,
  tune: TbAdjustmentsHorizontal,
  plug: TbPlugConnected,
  message: TbMessage2,
  search: TbSearch,
  edge: TbDeviceDesktopAnalytics,
  route: TbRoute,
  enterprise: TbBuildingSkyscraper,
  box: TbBox,
  flask: TbFlask,
  ml: TbChartDots3,
  heartbeat: TbHeartbeat,
  cart: TbShoppingCart,
  users: TbUsersGroup,
  hierarchy2: TbHierarchy2,
  bank: TbBuildingBank,
  shieldalert: TbShieldExclamation,
  activity: TbActivityHeartbeat,
  scan: TbScan,
  alarm: TbAlarm,
  truck: TbTruckDelivery,
  headset: TbHeadset,
  store: TbBuildingStore,
  orchestrator: TbHierarchy,
  trending: TbTrendingUp,
  mic: TbMicrophone,
  video: TbVideo,
  camera: TbCameraCheck,
  thumb: TbThumbUp,
};

export function AiOfferingIcon({ icon, className = "h-6 w-6 text-ss-mint" }: { icon: string; className?: string }) {
  const Icon = ICON_MAP[icon] ?? TbBrain;
  return <Icon className={className} aria-hidden />;
}
