import type { IconType } from "react-icons";
import {
  SiPython,
  SiTensorflow,
  SiPytorch,
  SiScikitlearn,
  SiJupyter,
  SiMlflow,
  SiDocker,
  SiApachekafka,
  SiPostgresql,
  SiLangchain,
  SiLanggraph,
  SiAnthropic,
  SiHuggingface,
  SiFlutter,
  SiReact,
  SiKotlin,
  SiSwift,
  SiExpo,
  SiFirebase,
  SiFastlane,
  SiAppium,
  SiSelenium,
  SiNextdotjs,
  SiTypescript,
  SiAngular,
  SiVuedotjs,
  SiExpress,
  SiNodedotjs,
  SiPhp,
  SiDotnet,
  SiSonarqubeserver,
  SiApachejmeter,
  SiGooglecloud,
  SiKubernetes,
  SiTerraform,
  SiGithubactions,
  SiJenkins,
  SiAnsible,
  SiPrometheus,
  SiGrafana,
  SiRedis,
  SiOdoo,
  SiBurpsuite,
  SiOwasp,
  SiVault,
  SiSnyk,
  SiGraphql,
  SiNumpy,
  SiPandas,
  SiKeras,
  SiOnnx,
  SiWeightsandbiases,
  SiApacheairflow,
  SiApachespark,
  SiN8N,
  SiTailwindcss,
  SiVite,
  SiCypress,
  SiJest,
  SiPostman,
  SiFigma,
  SiDigitalocean,
  SiCloudflare,
  SiNginx,
  SiGitlab,
  SiCircleci,
  SiElasticsearch,
  SiMongodb,
  SiMysql,
  SiSap,
  SiZendesk,
  SiMailchimp,
} from "react-icons/si";
import { FaAws } from "react-icons/fa6";
import {
  TbBrandAzure,
  TbBrandOpenai,
  TbBrandTwilio,
  TbStack2,
  TbDatabase,
  TbChartBar,
  TbMail,
  TbCode,
} from "react-icons/tb";

const ICON_MAP: Record<string, IconType> = {
  "python": SiPython,
  "tensorflow": SiTensorflow,
  "pytorch": SiPytorch,
  "scikit-learn": SiScikitlearn,
  "jupyter": SiJupyter,
  "mlflow": SiMlflow,
  "docker": SiDocker,
  "apache kafka": SiApachekafka,
  "postgresql": SiPostgresql,
  "langchain": SiLangchain,
  "langgraph": SiLanggraph,
  "openai api": TbBrandOpenai,
  "anthropic api": SiAnthropic,
  "pinecone": TbDatabase,
  "hugging face": SiHuggingface,
  "llamaindex": TbStack2,
  "flutter": SiFlutter,
  "react native": SiReact,
  "kotlin": SiKotlin,
  "swift": SiSwift,
  "expo": SiExpo,
  "firebase": SiFirebase,
  "fastlane": SiFastlane,
  "appium": SiAppium,
  "selenium": SiSelenium,
  "react": SiReact,
  "next.js": SiNextdotjs,
  "typescript": SiTypescript,
  "angular": SiAngular,
  "vue.js": SiVuedotjs,
  "express.js": SiExpress,
  "node.js": SiNodedotjs,
  "php": SiPhp,
  ".net": SiDotnet,
  "sonarqube": SiSonarqubeserver,
  "jmeter": SiApachejmeter,
  "aws": FaAws,
  "aws sagemaker": FaAws,
  "aws guardduty": FaAws,
  "azure": TbBrandAzure,
  "google cloud": SiGooglecloud,
  "kubernetes": SiKubernetes,
  "terraform": SiTerraform,
  "github actions": SiGithubactions,
  "jenkins": SiJenkins,
  "ansible": SiAnsible,
  "prometheus": SiPrometheus,
  "grafana": SiGrafana,
  "redis": SiRedis,
  "power bi": TbChartBar,
  "odoo": SiOdoo,
  "twilio": TbBrandTwilio,
  "sendgrid": TbMail,
  "burp suite": SiBurpsuite,
  "owasp zap": SiOwasp,
  "hashicorp vault": SiVault,
  "snyk": SiSnyk,
  "graphql": SiGraphql,
  "numpy": SiNumpy,
  "pandas": SiPandas,
  "keras": SiKeras,
  "onnx": SiOnnx,
  "weights & biases": SiWeightsandbiases,
  "apache airflow": SiApacheairflow,
  "apache spark": SiApachespark,
  "n8n": SiN8N,
  "tailwind css": SiTailwindcss,
  "vite": SiVite,
  "cypress": SiCypress,
  "jest": SiJest,
  "postman": SiPostman,
  "figma": SiFigma,
  "digitalocean": SiDigitalocean,
  "cloudflare": SiCloudflare,
  "nginx": SiNginx,
  "gitlab": SiGitlab,
  "circleci": SiCircleci,
  "elasticsearch": SiElasticsearch,
  "mongodb": SiMongodb,
  "mysql": SiMysql,
  "sap": SiSap,
  "zendesk": SiZendesk,
  "mailchimp": SiMailchimp,
};

export function TechIcon({ name, className = "h-5 w-5" }: { name: string; className?: string }) {
  const Icon = ICON_MAP[name.toLowerCase()] ?? TbCode;
  return <Icon className={className} aria-hidden />;
}
